packages:

  python-copr:
    downstream_package_name: python-copr
    upstream_package_name: copr
    paths: 
      - ./python
    specfile_path: python-copr.spec
    files_to_sync: 
      - python-copr.spec

  copr-cli:
    downstream_package_name: copr-cli
    upstream_package_name: copr-cli
    paths: 
      - ./cli
    specfile_path: copr-cli.spec
    files_to_sync: 
      - copr-cli.spec
