# .packit.yaml
specfile_path: python.spec
jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
    skip_build: true
    manual_trigger: true
    identifier: python-tests
    labels:
      - regression
    
